* About
This repository comprises of the sources and generation techniques for an IPAM working group on Tensor Methods in Quantum Chemistry. This work was undertaken over the course of the IPAM 2021 long program on tensor methods and emerging applications to the physical and data sciences.

- The compiled [[https://github.com/HaoZeke/ipam21_tqc_wg_report/blob/pdf/wgtqc.pdf][pdf can be viewed here]]
  - It is automatically built on each push
** Contributing
Please make changes in a PR to the ~org~ file. Some notes:
- We use ~biblatex~
- Enter a newline after each line, or ensure a maximum of 80 chars per line

Alternatively, for a simpler approach, upload your contribution as a word
document or something else and put it as an issue.
** Acknowledgments
*** Template
The template is a variant of the LaTeX [[https://www.latextemplates.com/template/the-legrand-orange-book][Legrand Orange Book]]. The base template is inspired liberally by the [[https://github.com/UppASD/UppASD/blob/master/docs/UppASDmanual.pdf][UppASD manual]].
The generation of this workflow is [[https://rgoswami.me/posts/org-arb-tex/][detailed here]].
