#+TITLE: Tensor Methods in Quantum Chemistry
#+SUBTITLE: An IPAM 2021 working group report
#+AUTHOR: Rohit Goswami
#+OPTIONS: toc:t \n:nil enable-local-variables:t
#+STARTUP: fninline
#+EXCLUDE_TAGS: noexport

* Configuration :ignoreheading:ignore:
  :PROPERTIES:
  :VISIBILITY: folded
  :END:
#+BEGIN_SRC emacs-lisp :exports none :eval always
(require 'ox-extra)
(ox-extras-activate '(ignore-headlines))
#+END_SRC

#+RESULTS:

** Theme :ignoreheading:ignore:
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
;; Details of this method: https://rgoswami.me/posts/org-arb-tex
(add-to-list 'org-latex-classes
             '("wgtex" "\\documentclass{wgtex}"
               ("\\part{%s}" . "\\part*{%s}")
               ("\\chapter{%s}" . "\\chapter*{%s}")
               ("\\section{%s}" . "\\section*{%s}")
               ("\\subsection{%s}" . "\\subsection*{%s}")
               ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
               ("\\paragraph{%s}" . "\\paragraph*{%s}")
               ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-minted-options 'nil)
(setq org-latex-listings 'minted)
(setq org-latex-default-packages-alist
  '(
    (""     "graphicx"  t)
    (""     "lipsum"  t)
;; Extra
;;    (""     "minted"   t)
    (""     "rotating"  nil)
    ("normalem" "ulem"  t)
    (""     "mathtools"   t)
    ))
#+END_SRC

*** TeX activation :ignoreheading:ignore:
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: wgtex
#+LATEX_HEADER: \setlength\parindent{0pt}
#+LATEX_HEADER: \addbibresource{wgtex.bib}
#+LATEX_HEADER: \usepackage{enumitem}
#+LATEX_HEADER: \setlist{nosep} % or \setlist{noitemsep} to leave space around whole list
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage[font={small}]{caption}

** Cover Page :ignoreheading:ignore:
# From https://tex.stackexchange.com/questions/101157/how-to-create-this-cover-page
#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \renewcommand{\maketitle}{%
#+LATEX_HEADER:     \begin{tikzpicture}[remember picture, overlay]
#+LATEX_HEADER:         % Gray boundary
#+LATEX_HEADER:         \node (left) at (current page.west)
#+LATEX_HEADER:               [rectangle, fill=gray, inner sep=0pt, anchor = west,
#+LATEX_HEADER:                minimum width=2cm, minimum height=1\paperheight]{};
#+LATEX_HEADER:         % Red boundary
#+LATEX_HEADER:         \node (bottom) at (current page.south)
#+LATEX_HEADER:               [rectangle, fill=BrickRed, inner sep=0 pt, anchor=south,
#+LATEX_HEADER:                minimum width=1\paperwidth, minimum height=0.5cm]{};
#+LATEX_HEADER:
#+LATEX_HEADER:         % Some additional stuff:
#+LATEX_HEADER:         \node [yshift=\paperheight/3] (middle) at (current page.south)
#+LATEX_HEADER:               [rectangle, fill=Green, inner sep=0pt, anchor=north west,
#+LATEX_HEADER:                minimum height=3cm, minimum width=0.25\paperwidth]{};
#+LATEX_HEADER:         \node [yshift=\paperheight/3] (middle) at (current page.south)
#+LATEX_HEADER:               [rectangle, fill=BrickRed, inner sep=0pt, anchor=north east,
#+LATEX_HEADER:                minimum height=3cm, minimum width=0.25\paperwidth]{};
#+LATEX_HEADER:         \node [yshift=\paperheight/3] (middle) at (current page.south)
#+LATEX_HEADER:               [rectangle, fill=Goldenrod, inner sep=0pt, anchor=south west,
#+LATEX_HEADER:                minimum height=3cm, minimum width=0.25\paperwidth]{};
#+LATEX_HEADER:         \node [yshift=\paperheight/3] (middle) at (current page.south)
#+LATEX_HEADER:               [rectangle, fill=RoyalBlue, inner sep=0pt, anchor=south east,
#+LATEX_HEADER:                minimum height=3cm, minimum width=0.25\paperwidth]{};
#+LATEX_HEADER:     \end{tikzpicture}
#+LATEX_HEADER:     \thispagestyle{empty}
#+LATEX_HEADER:     \parindent0pt
#+LATEX_HEADER:
#+LATEX_HEADER:     \begin{addmargin}{4em}
#+LATEX_HEADER:         \vspace{4cm}
#+LATEX_HEADER:         {\huge\usekomafont{title} \@title}
#+LATEX_HEADER:
#+LATEX_HEADER:         \vspace{2cm}
#+LATEX_HEADER:         {\usekomafont{disposition}\Large \@author}
#+LATEX_HEADER:     \end{addmargin}
#+LATEX_HEADER: }
#+LATEX_HEADER: \makeatother

* Start Here :ignoreheading:ignore:
* Context
** Scope
Rather than begin on a traditional introduction, we will start out by describing the context in which we are to cover the rest of this report.
The broader context of this working group is to gain a broad understanding of the use (and abuse) of tensor methods in quantum chemistry.
There is a lack of coherent material accessible to members of the community. In particular, though there has been a proliferation of user-friendly black box methods, there are few, if any strategies to bring researchers to a point where they are able to meaningfully contribute in a sustainable way to a software ecosystem.

We divide a problem into the physical model and it's numerical representation, followed by an approximation. This is the traditional approach which ignores the structure of programming.
# ** Basics
# #+begin_export latex
# \lipsum[2-3]
# #+end_export

# Now we can test some code:
# #+begin_src python :eval never :export code
# import antigravity
# print 'Hello world Hello world Hello world Hello world Hello world Hello world'
# #+end_src

# #+begin_export latex
# \begin{equationB}[The Landau-Lifshitz-Gilbert (LLG) equation]\index{Equation of motion}
# \begin{align*}
#  \frac{d\mathbf{m}_i}{dt}=-\frac{\gamma}{1+\alpha^2} \mathbf{m}_i \times [\mathbf{B}_{i}+\mathbf{b}_{i}(t)]-\frac{\gamma}{m_i} \frac{\alpha}{1+\alpha^2} \mathbf{m}_i \times (\mathbf{m}_i \times [\mathbf{B}_{i}+\mathbf{b}_{i}(t)])
# %
# \end{align*}
# \label{eq:sllg}
# \end{equationB}
# #+end_export
* Implementations
** Languages and DSLs
One of the common concerns
it isn’t really that these ideas are new, but they suffer from bitrot over time. BLOCK is now meant to be used as a black box, and the source is not distributed on Github; similarly, the Quantum Chemistry version of CTF, aquarius has also suffered from a lack of development. CTF is reasonably well developed, but it has fallen behind in terms of speed compared to the later stage libraries like the tensorflow accelerated opt einsum
** Cathedrals in Quantum Chemistry
Quantum chemistry has suffered for many years as a retarded child of computer science in terms of the communal adoption of closed source tools which can be traced back to the original sin of Gaussian going closed source. Lately, there has been a slight re calibration of the community’s moral compass in a positive sense, and several previously closed source packages have become open-source (e.g. the GAP potentials, d-SEAMS, lammps, gromacs).
* Conclusions
** Group Outputs
** Outlook
The purpose of outlining a grand unifying plan is to encourage the community to partake in its eventual sucess. We emphasize that the time has passed for disparate groups to struggle in closed source developments. Inclusive authorship like the NWChem paper is a laudable and achievable goal as a community. The recent sucesses of for-profit companies like Google and their ilk in academic arenas should further serve as a wakeup call; it is only in their ability to connect working scientists of various disciplines have their sucesses been assured.
GPAW holds monthly developer meetings, Stan likewise has developer hours, as do DeepChem and some other; however, these are still currently few and far apart. Contrary to some beliefs, these have not diluted the ability of the steering groups nor swamped the communities with frivolous demands. Recently, even the Fortran steering committee has opened a public forum (in the form of the J3 proposals repository) to bring more of the community into the decision making process. Computational chemistry, once one of the early adopters of the net has fallen behind, and it can only be hoped that programs like those held at IPAM will be able to stem the flow of bad practices and secrecy.

DMRG, ALS, these are bulletproof, concrete ideas, which need to be merged with the nebulous lexicon of quantum chemistry. Many avenues are unexplored, relativistic qc, electrostatics. Outlook, they're powerful, expressive tools which need to be coerced into the qc lexicon for efficient use.

* Bibliography :ignoreheading:ignore:
#+BEGIN_EXPORT latex
\newpage
\printbibliography[title=Bibliography]
#+END_EXPORT

* Local Variables :ignoreheading:ignore:
  :PROPERTIES:
  :VISIBILITY: folded
  :END:
# Local Variables:
# before-save-hook: org-babel-execute-buffer
# after-save-hook: (lambda () (org-latex-export-to-latex) t)
# End:
