name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install package
        run: |
          sudo apt-get install -y python-pygments emacs \
          texlive-full texlive-science texlive-xetex latexmk \
          texlive-bibtex-extra biber

      - name: Generate TeX
        run: |
          emacs -q -nl --script scripts/org2tex.el src/wgtqc.org

      - name: Build pdf
        run: |
          cd src/
          latexmk -pdfxe -shell-escape wgtqc.tex -f

      - name: Move pdf
        run: |
          mkdir pdfdir
          mv src/wgtqc.pdf pdfdir/wgtqc.pdf

      - name: Deploy pdf
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./pdfdir
          force_orphan: true
