name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install package
        run: |
          sudo apt-get install -y python-pygments emacs

      - name: Generate TeX
        run: |
          cd src
          emacs -q -nl --script ../scripts/org2tex.el wgtqc.org

      - name: Build pdf
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          root_file: wgtqc.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true

      - name: Deploy pdf
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: src/wgtqc.pdf
