name: Build PDF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive" # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Install package
        run: |
          sudo apt-get install -y python-pygments emacs

      - name: Setup LaTeX
        run: |
          scripts/getTexLive.sh $(pwd)/scripts/texlive.profile

      - name: Generate TeX
        run: |
          emacs -q -nl --script scripts/org2tex.el src/wgtqc.org

      - name: Cache texlive
        uses: actions/cache@v2
        id: cache-texlive
        with:
          path: |
            ~/texmf
            /tmp/texlive/
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Build pdf
        run: |
          export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
          export PATH=$HOME/texmf/bin:$PATH
          cd src/
          texliveonfly -c latexmk -a "-pdfxe -shell-escape -f" wgtqc.tex

      - name: Move pdf
        run: |
          mkdir pdfdir
          mv src/wgtqc.pdf pdfdir/wgtqc.pdf

      - name: Deploy pdf
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pdf
          publish_dir: ./pdfdir
          force_orphan: true
